//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brainy_Bunch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.Tender_Request = new HashSet<Tender_Request>();
        }
    
        public int Client_ID { get; set; }
        public string Client_Name { get; set; }
        public string Client_Address { get; set; }
        public string Contact_Person { get; set; }
        public Nullable<decimal> Telephone_Numbers { get; set; }
    
        public virtual ICollection<Tender_Request> Tender_Request { get; set; }
    }
}
