//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brainy_Bunch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Type
    {
        public Employee_Type()
        {
            this.Employees = new HashSet<Employee>();
            this.Employees1 = new HashSet<Employee1>();
            this.Employees2 = new HashSet<Employee2>();
        }
    
        public int Employee_Type_ID { get; set; }
        public string Employee_Type_Description { get; set; }
    
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<Employee1> Employees1 { get; set; }
        public virtual ICollection<Employee2> Employees2 { get; set; }
    }
}
