//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brainy_Bunch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public Equipment()
        {
            this.Tasks_Equipment = new HashSet<Tasks_Equipment>();
        }
    
        public int Equipment_ID { get; set; }
        public string Equipment_Name { get; set; }
        public string Equipment_Description { get; set; }
        public string Equipment_Condition { get; set; }
        public decimal Quantity { get; set; }
    
        public virtual ICollection<Tasks_Equipment> Tasks_Equipment { get; set; }
    }
}
