//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brainy_Bunch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory1
    {
        public Inventory1()
        {
            this.Inventory_On_Hand = new HashSet<Inventory_On_Hand>();
            this.Orderlines = new HashSet<Orderline1>();
            this.Phase_Inventory = new HashSet<Phase_Inventory>();
            this.Rental_Line = new HashSet<Rental_Line>();
        }
    
        public int Inventory_ID { get; set; }
        public int Category_ID { get; set; }
        public string Inventory_Name { get; set; }
        public string Inventory_Description { get; set; }
        public decimal Quantity { get; set; }
    
        public virtual Category1 Category { get; set; }
        public virtual ICollection<Inventory_On_Hand> Inventory_On_Hand { get; set; }
        public virtual ICollection<Orderline1> Orderlines { get; set; }
        public virtual ICollection<Phase_Inventory> Phase_Inventory { get; set; }
        public virtual ICollection<Rental_Line> Rental_Line { get; set; }
    }
}
