//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brainy_Bunch.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Gabriq_System_DatabaseEntities : DbContext
    {
        public Gabriq_System_DatabaseEntities()
            : base("name=Gabriq_System_DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Category> Categories { get; set; }
        public DbSet<Checkout_Checkin> Checkout_Checkin { get; set; }
        public DbSet<Checkout_Checkin_Date> Checkout_Checkin_Date { get; set; }
        public DbSet<Client> Clients { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<Employee_Task> Employee_Task { get; set; }
        public DbSet<Employee_Type> Employee_Type { get; set; }
        public DbSet<Equipment> Equipments { get; set; }
        public DbSet<Inventory> Inventories { get; set; }
        public DbSet<Inventory_On_Hand> Inventory_On_Hand { get; set; }
        public DbSet<Order_Status> Order_Status { get; set; }
        public DbSet<Orderline> Orderlines { get; set; }
        public DbSet<Password_History> Password_History { get; set; }
        public DbSet<Payment_Type> Payment_Type { get; set; }
        public DbSet<Phase> Phases { get; set; }
        public DbSet<Phase_Inventory> Phase_Inventory { get; set; }
        public DbSet<Phase_Status> Phase_Status { get; set; }
        public DbSet<Project> Projects { get; set; }
        public DbSet<Project_Status> Project_Status { get; set; }
        public DbSet<Rental> Rentals { get; set; }
        public DbSet<Rental_Line> Rental_Line { get; set; }
        public DbSet<Rental_Request> Rental_Request { get; set; }
        public DbSet<Rental_Request_Status> Rental_Request_Status { get; set; }
        public DbSet<Rental_Status> Rental_Status { get; set; }
        public DbSet<Subcontractor> Subcontractors { get; set; }
        public DbSet<Subcontractor_Phase> Subcontractor_Phase { get; set; }
        public DbSet<Supplier> Suppliers { get; set; }
        public DbSet<Supplier_Order> Supplier_Order { get; set; }
        public DbSet<Supplier_Request> Supplier_Request { get; set; }
        public DbSet<Supplier_Request_Status> Supplier_Request_Status { get; set; }
        public DbSet<Supplier_Type> Supplier_Type { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Task> Tasks { get; set; }
        public DbSet<Task_Status> Task_Status { get; set; }
        public DbSet<Tasks_Equipment> Tasks_Equipment { get; set; }
        public DbSet<Tender> Tenders { get; set; }
        public DbSet<Tender_Request> Tender_Request { get; set; }
        public DbSet<Tender_Request_Status> Tender_Request_Status { get; set; }
        public DbSet<Tender_Status> Tender_Status { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<User_Role> User_Role { get; set; }
        public DbSet<WriteOff_Inventory> WriteOff_Inventory { get; set; }
        public DbSet<Category1> Category1 { get; set; }
        public DbSet<Checkout_Checkin1> Checkout_Checkin1 { get; set; }
        public DbSet<Checkout_Checkin_Date1> Checkout_Checkin_Date1 { get; set; }
        public DbSet<Client1> Client1 { get; set; }
        public DbSet<Employee1> Employee1 { get; set; }
        public DbSet<Equipment1> Equipment1 { get; set; }
        public DbSet<Inventory1> Inventory1 { get; set; }
        public DbSet<Orderline1> Orderline1 { get; set; }
        public DbSet<Phase1> Phase1 { get; set; }
        public DbSet<Project1> Project1 { get; set; }
        public DbSet<Rental1> Rental1 { get; set; }
        public DbSet<Subcontractor1> Subcontractor1 { get; set; }
        public DbSet<Supplier1> Supplier1 { get; set; }
        public DbSet<Task1> Task1 { get; set; }
        public DbSet<Tender1> Tender1 { get; set; }
        public DbSet<User1> User1 { get; set; }
        public DbSet<Category2> Category2 { get; set; }
        public DbSet<Checkout_Checkin2> Checkout_Checkin2 { get; set; }
        public DbSet<Checkout_Checkin_Date2> Checkout_Checkin_Date2 { get; set; }
        public DbSet<Client2> Client2 { get; set; }
        public DbSet<Employee2> Employee2 { get; set; }
        public DbSet<Equipment2> Equipment2 { get; set; }
        public DbSet<Inventory2> Inventory2 { get; set; }
        public DbSet<Orderline2> Orderline2 { get; set; }
        public DbSet<Phase2> Phase2 { get; set; }
        public DbSet<Project2> Project2 { get; set; }
        public DbSet<Rental2> Rental2 { get; set; }
        public DbSet<Subcontractor2> Subcontractor2 { get; set; }
        public DbSet<Supplier2> Supplier2 { get; set; }
        public DbSet<Task2> Task2 { get; set; }
        public DbSet<Tender2> Tender2 { get; set; }
        public DbSet<User2> User2 { get; set; }
    }
}
