//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brainy_Bunch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orderline1
    {
        public int Orderline_ID { get; set; }
        public int Inventory_ID { get; set; }
        public string Inventory_Item { get; set; }
        public decimal Quantity { get; set; }
        public decimal Unit_Price { get; set; }
        public decimal Total_Cost { get; set; }
    
        public virtual Inventory1 Inventory { get; set; }
    }
}
