//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brainy_Bunch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment_Type
    {
        public Payment_Type()
        {
            this.Supplier_Order = new HashSet<Supplier_Order>();
        }
    
        public int Payment_Type_ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Supplier_Order> Supplier_Order { get; set; }
    }
}
