//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brainy_Bunch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phase_Status
    {
        public Phase_Status()
        {
            this.Phases = new HashSet<Phase>();
            this.Phases1 = new HashSet<Phase1>();
            this.Phases2 = new HashSet<Phase2>();
        }
    
        public int Phase_Status_ID { get; set; }
        public string Status_Type { get; set; }
    
        public virtual ICollection<Phase> Phases { get; set; }
        public virtual ICollection<Phase1> Phases1 { get; set; }
        public virtual ICollection<Phase2> Phases2 { get; set; }
    }
}
