//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brainy_Bunch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phase_Inventory
    {
        public int Phase_Inventory_ID { get; set; }
        public Nullable<int> Phase_ID { get; set; }
        public Nullable<int> Inventory_ID { get; set; }
        public Nullable<decimal> Quantity { get; set; }
    
        public virtual Inventory Inventory { get; set; }
        public virtual Phase Phase { get; set; }
        public virtual Inventory1 Inventory1 { get; set; }
        public virtual Phase1 Phase1 { get; set; }
        public virtual Inventory2 Inventory2 { get; set; }
        public virtual Phase2 Phase2 { get; set; }
    }
}
