//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brainy_Bunch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project_Status
    {
        public Project_Status()
        {
            this.Projects = new HashSet<Project>();
            this.Projects1 = new HashSet<Project1>();
            this.Projects2 = new HashSet<Project2>();
        }
    
        public int Project_Status_ID { get; set; }
        public string Description { get; set; }
        public string Comments { get; set; }
    
        public virtual ICollection<Project> Projects { get; set; }
        public virtual ICollection<Project1> Projects1 { get; set; }
        public virtual ICollection<Project2> Projects2 { get; set; }
    }
}
