//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brainy_Bunch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rental_Status
    {
        public Rental_Status()
        {
            this.Rentals = new HashSet<Rental>();
            this.Rentals1 = new HashSet<Rental1>();
            this.Rentals2 = new HashSet<Rental2>();
        }
    
        public int Rental_Status_ID { get; set; }
        public string Status_Type { get; set; }
    
        public virtual ICollection<Rental> Rentals { get; set; }
        public virtual ICollection<Rental1> Rentals1 { get; set; }
        public virtual ICollection<Rental2> Rentals2 { get; set; }
    }
}
