//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brainy_Bunch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subcontractor_Phase
    {
        public int Subcontractor_Phase_ID { get; set; }
        public Nullable<int> Subcontractor_ID { get; set; }
        public Nullable<int> Phase_ID { get; set; }
    
        public virtual Phase Phase { get; set; }
        public virtual Subcontractor Subcontractor { get; set; }
        public virtual Phase1 Phase1 { get; set; }
        public virtual Subcontractor1 Subcontractor1 { get; set; }
        public virtual Phase2 Phase2 { get; set; }
        public virtual Subcontractor2 Subcontractor2 { get; set; }
    }
}
