//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brainy_Bunch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subcontractor2
    {
        public Subcontractor2()
        {
            this.Subcontractor_Phase = new HashSet<Subcontractor_Phase>();
        }
    
        public int Subcontractor_ID { get; set; }
        public string Sub_Name { get; set; }
        public string Sub_Address { get; set; }
        public string Sub_Job_Description { get; set; }
        public string Telephone_Number { get; set; }
        public string Email_Address { get; set; }
    
        public virtual ICollection<Subcontractor_Phase> Subcontractor_Phase { get; set; }
    }
}
