//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brainy_Bunch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier_Request_Status
    {
        public Supplier_Request_Status()
        {
            this.Supplier_Request = new HashSet<Supplier_Request>();
        }
    
        public int Supplier_Request_Status_ID { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Supplier_Request> Supplier_Request { get; set; }
    }
}
