//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brainy_Bunch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier_Type
    {
        public Supplier_Type()
        {
            this.Suppliers = new HashSet<Supplier>();
            this.Suppliers1 = new HashSet<Supplier1>();
            this.Suppliers2 = new HashSet<Supplier2>();
        }
    
        public int Supplier_Type_ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Supplier> Suppliers { get; set; }
        public virtual ICollection<Supplier1> Suppliers1 { get; set; }
        public virtual ICollection<Supplier2> Suppliers2 { get; set; }
    }
}
