//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brainy_Bunch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_Status
    {
        public Task_Status()
        {
            this.Tasks = new HashSet<Task>();
            this.Tasks1 = new HashSet<Task1>();
            this.Tasks2 = new HashSet<Task2>();
        }
    
        public int Task_Status_ID { get; set; }
        public string Status_Type { get; set; }
    
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual ICollection<Task1> Tasks1 { get; set; }
        public virtual ICollection<Task2> Tasks2 { get; set; }
    }
}
