//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brainy_Bunch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tender1
    {
        public Tender1()
        {
            this.Projects = new HashSet<Project1>();
            this.Tender_Request = new HashSet<Tender_Request>();
        }
    
        public int Tender_ID { get; set; }
        public int Tender_Status_ID { get; set; }
        public string Tender_Name { get; set; }
        public string Tender_Source { get; set; }
        public decimal Budget { get; set; }
        public int Project_ID { get; set; }
    
        public virtual ICollection<Project1> Projects { get; set; }
        public virtual Project1 Project { get; set; }
        public virtual ICollection<Tender_Request> Tender_Request { get; set; }
        public virtual Tender_Status Tender_Status { get; set; }
    }
}
