//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brainy_Bunch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tender_Status
    {
        public Tender_Status()
        {
            this.Tenders = new HashSet<Tender>();
            this.Tenders1 = new HashSet<Tender1>();
            this.Tenders2 = new HashSet<Tender2>();
        }
    
        public int Tender_Status_ID { get; set; }
        public string Status_Type { get; set; }
    
        public virtual ICollection<Tender> Tenders { get; set; }
        public virtual ICollection<Tender1> Tenders1 { get; set; }
        public virtual ICollection<Tender2> Tenders2 { get; set; }
    }
}
