//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brainy_Bunch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tender_Request_Status
    {
        public Tender_Request_Status()
        {
            this.Tender_Request = new HashSet<Tender_Request>();
        }
    
        public int Tender_Request_Status_ID { get; set; }
        public string Status_Type { get; set; }
    
        public virtual ICollection<Tender_Request> Tender_Request { get; set; }
    }
}
