//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brainy_Bunch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Role
    {
        public User_Role()
        {
            this.Users = new HashSet<User>();
            this.Users1 = new HashSet<User1>();
            this.Users2 = new HashSet<User2>();
        }
    
        public int User_Role_ID { get; set; }
        public string Role_Name { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<User1> Users1 { get; set; }
        public virtual ICollection<User2> Users2 { get; set; }
    }
}
